name: MyWorkflow

on: 
  push:
    branches:
      - master

jobs:
  MY_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: |
          echo "Hello From step WELCOME"
          echo "Procjects: ls- la"
          ls -la
      - name: copy project
        uses: actions/checkout@v3.0.2
      - name: LS PROJECT
        run: |
          echo "Procjects: ls- la"
          ls -la

  MY_CD:
    runs-on: ubuntu-latest
    needs: MY_testing
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.2
      - name: install sshpass
        run: sudo apt install sshpass
      - name: executing remote ssh commands using password
      - name: SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          script: whoami
      
      # - name: connect
      #   run: |
      #     sshpass -p ${{ secrets.PASS }} ${{ secrets.USER }}"@"${{ secrets.IP }} -o StrictHostKeyChecking=no
        # run: |
        #   sshpass -p "${{ secrets.PASS }}" ssh \
        #   -o StrictHostKeyChecking=no \
        #   "${{ secrets.USER }}"@"${{ secrets.IP }}" \
        #   "ls -la"
    
  
  
    
