name: MyWorkflow_

on: 
  push:
    branches:
      - master

jobs:
  MY_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: |
          echo "Hello From step WELCOME"
          echo "Procjects: ls- la"
          ls -la
      - name: copy project
        uses: actions/checkout@v1
      - name: copy project
        run: |
          echo "Procjects: ls- la"
          ls -la

  MY_CD:
    runs-on: ubuntu-latest
    needs: MY_testing
    steps:
      - name: checkout
      - uses: actions/checkhout@v1
      - name: connect
        run: |
          ssh -p ${{ env.PASS }} ${{ env.USER }}@${{ env.HOST }}
          pwd
          
    
  
  
    
