name: MyWorkflow

on: 
  push:
    branches:
      - master

jobs:
  MY_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: |
          echo "Hello From step WELCOME"
          echo "Procjects: ls- la"
          ls -la
      - name: copy project
        uses: actions/checkout@v3.0.2
      - name: LS PROJECT
        run: |
          echo "Procjects: ls- la"
          ls -la

  MY_CD:
    runs-on: ubuntu-latest
    needs: MY_testing
    env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY_UNPUB}}
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.2
      - name: install ssh
        run: sudo apt install openssh-client
  
      # - name: SSH
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.IP }}
      #     username: ${{ secrets.USER }}
      #     password: ${{ secrets.PASS }}
      #     script: whoami

      - name: SSH
        run: |
          cd ~ && sudo touch sshkey 
          sudo chmod 777 sshkey 
          sudo echo "$SSH_PRIVATE_KEY"> sshkey 
          
          ssh -i ./sshkey -o StrictHostKeyChecking=no ${{ secrets.USER }}"@"${{ secrets.IP }} << 'EOF'
          # Команды, которые будут выполнены на удаленном сервере
          cd /path/to/your/project
          git pull origin main
          npm install
          npm run build
          sudo systemctl restart your-service
          EOF
      
      # - name: connect
      #   run: |
      #     sshpass -p ${{ secrets.PASS }} ${{ secrets.USER }}"@"${{ secrets.IP }} -o StrictHostKeyChecking=no
        # run: |
        #   sshpass -p "${{ secrets.PASS }}" ssh \
        #   -o StrictHostKeyChecking=no \
        #   "${{ secrets.USER }}"@"${{ secrets.IP }}" \
        #   "ls -la"
    
  
  
    
